---

- name: "Terminate Provisioner"
  hosts: localhost
  gather_facts: no

  tasks:
  - name: "Get DNS record for provisioner"
    route53:
      state: get
      zone: lab-emergent360.com
      record: provision-"{{ stage }}".lab-emergent360.com
      type: A
    register: rec
    
  - name: "Remove DNS record for provisioner"
    route53:
      state: absent
      zone: lab-emergent360.com
      record: "{{ rec.set.record }}"
#      type: "{{ rec.set.type }}"
#      value: "{{ rec.set.value }}"
    when: rec.set

  - name: "Get instance ID"
    ec2_instance_info:
      filters:
        "tag:Name": "Workshop Provisioner {{ stage | capitalize }}"
    register: ec2

  - name: "Terminate instance"
    ec2_instance:
      state: absent
      instance_ids: "{{ ec2.instances[0].instance_id }}"




    